/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e2e2eb",
        "secondary": "#69f6b8",
        "tertiary": "#ffb783",
        "primary-fixed-dim": "#69f6b8",
        "inverse-surface": "#e2e2eb",
        "surface-container-lowest": "#0c0e14",
        "error": "#ffb4ab",
        "on-surface-variant": "#aaaab3",
        "primary": "#69f6b8",
        "on-error": "#003923",
        "on-primary": "#003923",
        "surface-tint": "#69f6b8",
        "background": "#0c0e14",
        "tertiary-container": "#d97721",
        "secondary-container": "#005235",
        "primary-fixed": "#86ffd0",
        "on-secondary-container": "#86ffd0",
        "outline-variant": "#464554",
        "surface-variant": "#33343b",
        "inverse-on-surface": "#2e3037",
        "outline": "#74757d",
        "on-surface": "#e2e2eb",
        "on-primary-container": "#002114",
        "surface-container": "#171921",
        "on-error-container": "#ffdad6",
        "surface-dim": "#111319",
        "surface-bright": "#373940",
        "on-primary-fixed-variant": "#005235",
        "inverse-primary": "#006d48",
        "surface-container-highest": "#23262e",
        "surface-container-low": "#11131a",
        "on-primary-fixed": "#002114",
        "surface": "#0c0e14",
        "on-secondary": "#003923",
        "primary-container": "#06b77f",
        "on-tertiary-fixed": "#301400",
        "surface-container-high": "#1d1f27",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdcc5",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
